#!/bin/sh

#
# Script used by hostapps updater to flash bootloader onto internal media
#

set -o errexit

# machine specific data
bootloader_file="idbloader.img"
block_size=512
seek_blocks=64
device="/dev/mmcblk0"

# size and md5sum of the bootloader from the update bundle
update_bootloader_size=$(ls -al /resin-boot/$bootloader_file | awk '{print $5}')
update_bootloader_md5sum=$(md5sum /resin-boot/$bootloader_file | awk '{print $1'})

# number of bytes to skip when calculating the existing bootloader checksum
let skip_bytes=$block_size*$seek_blocks

# calculate md5sum of $update_bootloader_size bytes, skipping $skip_bytes from $device
existing_bootloader_md5sum=$(dd if=$device skip=$skip_bytes bs=1 count=$update_bootloader_size status=none | md5sum | awk '{print $1}')

if [ ! "$existing_bootloader_md5sum" = "$update_bootloader_md5sum" ]; then
    dd if=/resin-boot/$bootloader_file of=$device conv=fdatasync seek=$seek_blocks bs=$block_size
fi
